"""2_launcher.py -- the one entry point for the risk monitor (setup and launch). The repo
root holds exactly three files, sorted in the order you use them: `1_setup.cmd` (for a PC
that doesn't have Python or git yet), this file, and `3_diagnostic.py` (Bloomberg
diagnostics).

    py 2_launcher.py setup      install everything into .venv, create the database, run the tests
    py 2_launcher.py start      start the app (opens the browser)
    py 2_launcher.py doctor     check every prerequisite and say exactly what to fix
    py 2_launcher.py freeze     (re)write requirements.txt from the list below, for `pip install -r`
                                 or CI that doesn't go through this file

Backfilling P&L history from Bloomberg daily closes is automatic: `start` and every
Bloomberg feed cycle in data/bloomberg/live.py trigger it in the background (see
data/bloomberg/backfill.py). There is no separate command for it.

`setup` runs with whatever Python launched it and creates `.venv` beside this file.
Every other command re-runs itself inside `.venv` so the packages installed by
`setup` are the ones the app uses. No batch files, no PATH edits, no global pip.
Standard library only in this file: it must import before anything is installed.

Every third-party package the app needs, in one place (PACKAGES below), instead of a
separate requirements.txt: `setup` installs straight from this list, and `doctor` /
`setup`'s own verify step import-check IMPORT_CHECKS. Keeping both in this one file is
what stops the "installed but not checked" / "checked but not installed" gap that bit us
once already (numpy, pyyaml, QuantLib were imported by engine/ui code but missing from
an earlier version of both lists). `requirements.txt` itself is not checked in; run
`py 2_launcher.py freeze` if some external tool (CI, `pip install -r requirements.txt`) needs
the file on disk -- it is regenerated from PACKAGES, never edited by hand.
"""
from __future__ import annotations

import argparse
import os
import platform
import socket
import sqlite3
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV = ROOT / ".venv"
VENV_PY = VENV / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
REQUIREMENTS = ROOT / "requirements.txt"
SAMPLE = ROOT / "data" / "sample" / "blotter_sample.csv"
BLPAPI_INDEX = "https://blpapi.bloomberg.com/repository/releases/python/simple/"
MIN_PYTHON = (3, 11)
PORTS = range(8050, 8061)
TABLES = ("instruments", "trades", "trade_legs", "marks", "positions", "realised_pnl")

# Every third-party package `pip install`s (blpapi is separate: special index, PC-conditional).
# Comment marks *why* each one is here so a future removal of the corresponding import can
# remove the right line instead of leaving a dangling dependency.
PACKAGES = [
    "dash>=4.4,<5",       # ui/ -- the app itself
    "pandas>=3,<4",       # data/ingest, data/bloomberg, engine/ -- blotter CSV/xlsx parsing, series math
    "numpy>=2,<3",        # engine/ -- pnl/ladder/rates numeric work
    "openpyxl>=3.1,<4",   # data/ingest/workbook_rates.py -- .xlsx read
    "xlrd>=2,<3",         # data/ingest -- legacy .xls read
    "plotly",             # ui/tabs/market_data.py imports plotly.graph_objects directly
    "werkzeug>=3,<4",     # ui/launch.py imports werkzeug.serving.make_server directly
    "tzdata",             # zoneinfo has no system tz database on Windows; needed at runtime, no import statement
    "pyyaml>=6.0",        # engine/pnl/stress.py imports this as `yaml`
    "QuantLib==1.43",     # engine/rates, engine/options -- curve bootstrap and option pricing
    "scipy>=1.11",        # engine/options/vendor/options_calc -- implied-vol solvers (scipy.optimize.brentq)
]
DEV_PACKAGES = [
    "pytest>=8",          # tests/
]
# Modules `doctor` / `setup` import-check after install, to catch "pip said OK but the
# module doesn't actually import" (wrong wheel, ABI mismatch, etc). zoneinfo is stdlib
# (3.9+) but still checked since tzdata above depends on it existing.
IMPORT_CHECKS = ("dash", "pandas", "numpy", "openpyxl", "xlrd", "plotly", "werkzeug",
                  "yaml", "QuantLib", "zoneinfo", "scipy")


def requirements_text() -> str:
    lines = [
        "# GENERATED by `py 2_launcher.py freeze` from the PACKAGES list in 2_launcher.py -- do not edit",
        "# by hand, it will be overwritten. `py 2_launcher.py setup` does not read this file; it",
        "# installs PACKAGES directly. This file exists only for `pip install -r requirements.txt`",
        "# or CI that doesn't go through 2_launcher.py.",
        *PACKAGES,
        "# blpapi is NOT listed here: `py 2_launcher.py setup` installs it from Bloomberg's own index",
        "# (" + BLPAPI_INDEX + ") on the Bloomberg PC.",
        *DEV_PACKAGES,
        "",
    ]
    return "\n".join(lines)


def cmd_freeze(args) -> int:
    REQUIREMENTS.write_text(requirements_text(), encoding="utf-8")
    say(f"wrote {REQUIREMENTS}")
    return 0


# ----------------------------------------------------------------------------- helpers

def say(msg: str = "") -> None:
    print(msg, flush=True)


def run(cmd: list, check: bool = True, **kw) -> int:
    say("  > " + " ".join(str(c) for c in cmd))
    code = subprocess.call([str(c) for c in cmd], cwd=str(ROOT), **kw)
    if check and code != 0:
        raise SystemExit(f"FAILED (exit {code}): {' '.join(str(c) for c in cmd)}")
    return code


def in_venv() -> bool:
    try:
        return Path(sys.executable).resolve() == VENV_PY.resolve()
    except OSError:
        return False


def reexec_in_venv(argv: list) -> int:
    """Run this script again under .venv. Returns its exit code."""
    if not VENV_PY.exists():
        say("No .venv yet. Double-click 1_setup.cmd (or run:  py 2_launcher.py setup), then try again.")
        return 2
    env = dict(os.environ, RISK_MONITOR_VENV="1")
    return subprocess.call([str(VENV_PY), str(ROOT / "2_launcher.py"), *argv], cwd=str(ROOT), env=env)


PNL_MARKER = "# --- risk-monitor pnl function (installed by `setup`) ---"
PNL_END_MARKER = "# --- end risk-monitor pnl function ---"
# Neither marker names the launcher file: they must stay byte-for-byte stable across a
# rename of this file (e.g. risk.py -> 2_launcher.py, 2026-09-16) so install_pnl_function()
# still recognises and replaces a block written by an older version of this script, instead
# of leaving a stale copy behind and appending a second one.
# A profile installed before 2026-09-16 carries this exact older marker instead; kept here
# so install_pnl_function() still finds and replaces it rather than duplicating the block.
LEGACY_PNL_MARKER = "# --- risk-monitor pnl function (installed by risk.py setup) ---"


def pnl_function_block() -> str:
    """The `pnl` PowerShell function, pinned to this clone's actual path. It only changes
    directory and calls `start`: the GitHub sync (fetch, stash local edits, fast-forward,
    reinstall packages if the code changed) lives in `sync_with_github` below so it runs
    identically from `pnl`, from `py 2_launcher.py start` and from an old profile."""
    return (
        f"{PNL_MARKER}\n"
        "function pnl {\n"
        f"    Set-Location '{ROOT}'\n"
        "    py -3 2_launcher.py start\n"
        "}\n"
        f"{PNL_END_MARKER}\n"
    )


def _git(*args, timeout: int = 90) -> tuple:
    r = subprocess.run(["git", *args], cwd=str(ROOT), capture_output=True, text=True, timeout=timeout)
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def sync_with_github() -> tuple:
    """Bring this clone to origin/main before the app starts, whatever state it is in.
    Returns (changed, message). Never raises and never blocks a start: offline, a
    non-git folder or a clone with unpushed commits (the dev machine) just runs the code
    on disk and says so. Local edits and untracked files on a user PC are stashed (`git
    stash list` / `git stash pop` to get them back), so a stray file can no longer pin a
    PC to old code silently -- the failure mode seen on 2026-09-17."""
    if not (ROOT / ".git").exists():
        return False, "not a git clone; running the code on disk"
    try:
        code, _, err = _git("fetch", "origin", "main", "--quiet")
    except (OSError, subprocess.SubprocessError) as exc:
        return False, f"git unavailable ({exc.__class__.__name__}); running the code on disk"
    if code != 0:
        last = (err.splitlines() or ["no detail"])[-1]
        return False, f"GitHub unreachable ({last}); running the code on disk"
    _, local, _ = _git("rev-parse", "HEAD")
    _, remote, _ = _git("rev-parse", "origin/main")
    if local == remote:
        return False, f"code {local[:7]} is current with GitHub"
    _, ahead, _ = _git("rev-list", "--count", "origin/main..HEAD")
    if ahead not in ("", "0"):
        return False, f"{ahead} local commit(s) not on GitHub; not updating (push them first), running {local[:7]}"
    _, dirty, _ = _git("status", "--porcelain")
    note = ""
    if dirty:
        import datetime as _dt
        stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M")
        code, _, err = _git("stash", "push", "--include-untracked", "-m", f"launcher auto-stash {stamp}")
        if code != 0:
            return False, f"could not set local edits aside ({err.splitlines()[-1] if err else 'no detail'}); running {local[:7]}"
        note = " -- local edits were set aside with git stash (git stash pop restores them)"
    code, _, err = _git("merge", "--ff-only", "origin/main")
    if code != 0:
        return False, f"update failed ({err.splitlines()[-1] if err else 'no detail'}); running {local[:7]}"
    return True, f"UPDATED {local[:7]} -> {remote[:7]}{note}"


def _profile_paths() -> list:
    """Windows PowerShell 5.1 and PowerShell 7+ profile paths, respecting Documents
    redirection (OneDrive etc.)."""
    try:
        import ctypes.wintypes
        CSIDL_PERSONAL = 5
        buf = ctypes.create_unicode_buffer(1024)
        ctypes.windll.shell32.SHGetFolderPathW(None, CSIDL_PERSONAL, None, 0, buf)
        docs = Path(buf.value) if buf.value else Path.home() / "Documents"
    except Exception:
        docs = Path.home() / "Documents"
    return [docs / "WindowsPowerShell" / "profile.ps1", docs / "PowerShell" / "profile.ps1"]


def install_pnl_function() -> list:
    """Add the `pnl` function to every PowerShell profile, replacing a previous copy of
    the block if present so repeat runs never duplicate it. Returns the profile paths
    written. Standard library only (ctypes), so this also runs before `setup` installs
    anything into .venv."""
    block = pnl_function_block()
    written = []
    for profile in _profile_paths():
        profile.parent.mkdir(parents=True, exist_ok=True)
        text = profile.read_text(encoding="utf-8") if profile.exists() else ""
        marker = PNL_MARKER if PNL_MARKER in text else (
            LEGACY_PNL_MARKER if LEGACY_PNL_MARKER in text else None)
        if marker is not None:
            start = text.index(marker)
            end = text.index(PNL_END_MARKER) + len(PNL_END_MARKER)
            # consume one trailing newline so re-writes don't grow blank lines
            after = end + 1 if text[end:end + 1] == "\n" else end
            text = text[:start] + block + text[after:]
        else:
            sep = "\n" if text and not text.endswith("\n") else ""
            text = text + sep + block
        profile.write_text(text, encoding="utf-8")
        written.append(str(profile))
    return written


def tcp_open(host: str, port: int, timeout: float = 0.5) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


def bloomberg_host() -> tuple:
    return os.environ.get("BLP_HOST", "localhost"), int(os.environ.get("BLP_PORT", "8194"))


def bloomberg_pc() -> bool:
    """Heuristic: a Terminal is installed or answering on the API port."""
    host, port = bloomberg_host()
    return Path("C:/blp").exists() or tcp_open(host, port)


def db_path() -> Path:
    raw = os.environ.get("RISK_DB")
    if raw:
        p = Path(raw)
        return p if p.is_absolute() else ROOT / p
    return ROOT / "data" / "raw" / "risk.db"


# ----------------------------------------------------------------------------- setup

def cmd_setup(args) -> int:
    say("=" * 70)
    say(f" risk-monitor setup   ({ROOT})")
    say("=" * 70)

    # 1. interpreter
    v = sys.version_info
    bits = platform.architecture()[0]
    say(f"[1/7] Python {v.major}.{v.minor}.{v.micro} {bits} at {sys.executable}")
    if v < MIN_PYTHON:
        say(f"FAILED: Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ is required. Install 64-bit Python from python.org,")
        say("        tick 'py launcher', then run:  py 2_launcher.py setup")
        return 1
    if bits != "64bit":
        say("FAILED: 64-bit Python is required (blpapi and pandas wheels are 64-bit).")
        return 1

    # 2. venv
    say("[2/7] Virtual environment")
    if args.recreate and VENV.exists():
        import shutil
        shutil.rmtree(VENV)
        say("  removed old .venv")
    if VENV_PY.exists():
        say(f"  OK: {VENV} exists")
    else:
        run([sys.executable, "-m", "venv", str(VENV)])
        say(f"  OK: created {VENV}")

    # 3. packages
    say("[3/7] Application packages")
    run([VENV_PY, "-m", "pip", "install", "--upgrade", "pip", "--quiet"], check=False)
    run([VENV_PY, "-m", "pip", "install", *PACKAGES, *DEV_PACKAGES, "--quiet"])
    say(f"  OK: {len(PACKAGES) + len(DEV_PACKAGES)} packages installed (see PACKAGES in 2_launcher.py)")

    # 4. blpapi (Bloomberg PC only)
    say("[4/7] Bloomberg API package")
    want_blp = args.bloomberg or (not args.no_bloomberg and bloomberg_pc())
    if want_blp:
        code = run([VENV_PY, "-m", "pip", "install", "--index-url", BLPAPI_INDEX, "blpapi"], check=False)
        if code != 0:
            say("FAILED: blpapi did not install. This PC must reach blpapi.bloomberg.com. Re-run later,")
            say("        or run  py 2_launcher.py setup --no-bloomberg  on a PC without a Terminal.")
            return 1
        say("  OK: blpapi installed")
    else:
        say("  skipped: no Bloomberg Terminal detected (use --bloomberg to force)")

    # 5. verify + database
    say("[5/7] Verify imports, create database and status file")
    check = (
        f"import {', '.join(IMPORT_CHECKS)};"
        "print('  OK: dash', dash.__version__, '| pandas', pandas.__version__);"
        "from ui.app import ensure_schema, get_db_path; ensure_schema(get_db_path());"
        "print('  OK: database', get_db_path())"
    )
    run([VENV_PY, "-c", check])
    if args.sample:
        run([VENV_PY, str(ROOT / "2_launcher.py"), "_load_sample"])

    # 6. pnl PowerShell function
    say("[6/7] 'pnl' PowerShell command")
    try:
        for profile in install_pnl_function():
            say(f"  OK: {profile}")
    except OSError as exc:
        say(f"FAILED: could not write PowerShell profile: {exc}")
        return 1

    # 7. tests
    say("[7/7] Tests")
    if args.skip_tests:
        say("  skipped (--skip-tests)")
    else:
        run([VENV_PY, "-m", "pytest", "tests/", "-q"])

    say()
    say("=" * 70)
    say(" SETUP COMPLETE.   Start the app:   py 2_launcher.py start")
    say("                   Anything wrong:  py 2_launcher.py doctor")
    if want_blp:
        say("                   Log in to the Bloomberg Terminal before starting.")
    say("=" * 70)
    return 0


def cmd_load_sample(args) -> int:
    """Import the sample trade blotter (runs inside .venv). Re-running it is harmless:
    the import is idempotent, so trades already present are replaced, not duplicated."""
    from ui.app import get_db_path
    from data.ingest.upload import import_blotter
    say("  sample: " + str(import_blotter(SAMPLE.read_bytes(), SAMPLE.name, get_db_path())))
    return 0


# ----------------------------------------------------------------------------- start

def cmd_start(args) -> int:
    if not in_venv():
        if not args.no_sync:
            changed, message = sync_with_github()
            say(f"GitHub: {message}")
            if changed:
                # The file now on disk may be newer than this running copy: hand over to
                # it (and let it refresh the packages) rather than continue with old code.
                argv = [a for a in sys.argv[1:] if a != "--no-sync"] + ["--no-sync", "--refresh-packages"]
                return subprocess.call([sys.executable, str(ROOT / "2_launcher.py"), *argv], cwd=str(ROOT))
        if args.refresh_packages and VENV_PY.exists():
            say("Code changed: refreshing packages in .venv")
            run([VENV_PY, "-m", "pip", "install", *PACKAGES, *DEV_PACKAGES, "--quiet"], check=False)
        return reexec_in_venv([a for a in sys.argv[1:] if a not in ("--no-sync", "--refresh-packages")])
    from ui.launch import main
    return main(["--force-new"] if args.force_new else [])


# ----------------------------------------------------------------------------- doctor

class Doctor:
    """Collects checks as (name, ok, detail, fix). `ok` may be None = informational."""

    def __init__(self):
        self.rows: list = []

    def add(self, name, ok, detail="", fix=""):
        self.rows.append((name, ok, detail, fix))
        label = "OK    " if ok else ("INFO  " if ok is None else "FAILED")
        say(f"[{label}] {name:14s} {detail}")
        if fix and ok is False:
            say(f"         fix -> {fix}")

    @property
    def failures(self):
        return [r for r in self.rows if r[1] is False]


def doctor_checks(d: Doctor, bloomberg: bool, git: bool = True) -> None:
    v = sys.version_info
    d.add("python", v >= MIN_PYTHON and platform.architecture()[0] == "64bit",
          f"{v.major}.{v.minor}.{v.micro} {platform.architecture()[0]} at {sys.executable}",
          "install 64-bit Python 3.11+ and run  py 2_launcher.py setup")

    d.add("venv", in_venv(), str(VENV) if in_venv() else "not running inside .venv",
          "py 2_launcher.py setup")

    missing = []
    for mod in IMPORT_CHECKS:
        try:
            __import__(mod)
        except ImportError:
            missing.append(mod)
    d.add("packages", not missing, "all application packages import" if not missing else "missing: " + ", ".join(missing),
          "py 2_launcher.py setup")

    # database
    p = db_path()
    if not p.exists():
        d.add("database", False, f"{p} does not exist", "py 2_launcher.py setup   (creates it empty)")
    else:
        try:
            conn = sqlite3.connect(f"file:{p.as_posix()}?mode=ro", uri=True)
            try:
                have = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
                lacking = [t for t in TABLES if t not in have]
                counts = {t: conn.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] for t in TABLES if t in have}
            finally:
                conn.close()
            if lacking:
                d.add("database", False, f"{p} lacks tables: {', '.join(lacking)}", "py 2_launcher.py setup   (applies the schema)")
            else:
                asof = counts.get("positions", 0)
                d.add("database", True, f"{p}: {counts.get('trades', 0)} trades, {asof} positions, "
                                        f"{counts.get('marks', 0)} marks")
                if counts.get("trades", 0) == 0:
                    d.add("data", None, "database is empty: press 'Upload trade file' in the app (the trade blotter export), or  py 2_launcher.py setup --sample")
        except sqlite3.Error as exc:
            d.add("database", False, f"{p}: {exc}", "the file is not a valid SQLite database; restore it from backup")

    status = p.with_name(p.name + ".bloomberg_status.json")
    d.add("status file", None if status.exists() else False,
          str(status) if status.exists() else "missing (created on start)", "py 2_launcher.py start")

    # bloomberg
    host, port = bloomberg_host()
    try:
        import blpapi  # noqa: F401
        have_blp = True
    except ImportError:
        have_blp = False
    terminal = tcp_open(host, port)
    if bloomberg:
        d.add("blpapi", have_blp, "installed" if have_blp else "not installed in .venv", "py 2_launcher.py setup --bloomberg")
        d.add("terminal", terminal, f"{host}:{port} {'answers' if terminal else 'no answer'}",
              "log in to the Bloomberg Terminal on this PC, then retry")
    else:
        d.add("bloomberg", None, ("blpapi installed, " if have_blp else "blpapi not installed, ")
              + (f"Terminal answers on {host}:{port}" if terminal else "no Terminal on this PC")
              + "  (run  py 2_launcher.py doctor --bloomberg  on the Bloomberg PC)")
    try:
        import json
        st = json.loads(status.read_text()) if status.exists() else None
        if st:
            d.add("last pull", None, f"{st.get('time')}: connected={st.get('connected')}, "
                                     f"written={st.get('written')}, failed={st.get('failed')}, "
                                     f"{st.get('reason', '')}".strip(", "))
    except (OSError, ValueError):
        pass

    # running instances
    try:
        from ui.launch import probe, source_fingerprint, identity, IDENTITY_PREFIX
        me = identity(source_fingerprint())
        found = []
        for pt in PORTS:
            seen = probe(f"http://127.0.0.1:{pt}")
            if seen is None:
                continue
            if seen == me:
                found.append(f"{pt}: current code")
            elif seen.startswith(IDENTITY_PREFIX):
                found.append(f"{pt}: STALE code {seen}")
            else:
                found.append(f"{pt}: another application")
        d.add("ports", None, "; ".join(found) if found else "nothing listening on 8050-8060 (start will use 8050)")
        if any("STALE" in f for f in found):
            d.add("stale app", False, "an old copy of the app is still running", "close its terminal window, then  py 2_launcher.py start")
    except ImportError as exc:
        d.add("ports", False, f"cannot import ui.launch: {exc}", "py 2_launcher.py setup")

    # git
    if git and (ROOT / ".git").exists():
        def g(*a):
            r = subprocess.run(["git", *a], cwd=str(ROOT), capture_output=True, text=True)
            return r.returncode, r.stdout.strip(), r.stderr.strip()
        code, branch, _ = g("branch", "--show-current")
        if code == 0:
            fcode, _, err = g("fetch", "origin", "--quiet")
            if fcode != 0 or "error" in err.lower():
                lines = err.splitlines() or ["no detail"]
                last = next((ln for ln in lines if ln.startswith("fatal")), lines[-1])
                d.add("git", False, f"fetch failed: {last}",
                      "offline -> ignore. 'bad object refs/...' -> delete that stale ref:  git update-ref -d <ref>")
            else:
                _, ahead, _ = g("rev-list", "--count", f"origin/{branch}..HEAD")
                _, behind, _ = g("rev-list", "--count", f"HEAD..origin/{branch}")
                _, dirty, _ = g("status", "--porcelain")
                msg = f"branch {branch}: {ahead} to push, {behind} to pull" + (", uncommitted changes" if dirty else "")
                d.add("git", ahead == "0" and behind == "0", msg,
                      "git pull" if behind != "0" else "git push")
        else:
            d.add("git", None, "git not available")


def cmd_doctor(args) -> int:
    if not in_venv() and VENV_PY.exists():
        return reexec_in_venv(sys.argv[1:])
    say("=" * 70)
    say(f" risk-monitor doctor   ({ROOT})")
    say("=" * 70)
    d = Doctor()
    doctor_checks(d, bloomberg=args.bloomberg, git=not args.no_git)
    code = 0
    if args.bloomberg:
        say()
        say("Bloomberg request-by-request check (read-only, reports under reports/):")
        code = run([sys.executable, str(ROOT / "tools" / "bloomberg_terminal_probe.py"), "--once"], check=False)
        d.add("bbg requests", code == 0, "every spot/forward request answered" if code == 0 else "see FAILED lines above",
              "read the Bloomberg error text above; reports/bloomberg_diagnostic_*.txt has the detail")
    if args.tests:
        say()
        tcode = run([sys.executable, "-m", "pytest", "tests/", "-q"], check=False)
        d.add("tests", tcode == 0, "all passed" if tcode == 0 else "failures above", "the code is broken: git pull, or report the failing test")
    say()
    say("=" * 70)
    if d.failures:
        say(f" {len(d.failures)} problem(s). Fix the first one, then run  py 2_launcher.py doctor  again:")
        for name, _, detail, fix in d.failures:
            say(f"   - {name}: {detail}")
            if fix:
                say(f"       fix -> {fix}")
        say("=" * 70)
        return 1
    say(" Everything checks out.   Start the app:  py 2_launcher.py start")
    say("=" * 70)
    return 0


# ----------------------------------------------------------------------------- cli

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="py 2_launcher.py", description="risk-monitor: setup, start, doctor.")
    sub = parser.add_subparsers(dest="command", required=True)

    s = sub.add_parser("setup", help="install everything into .venv, create the database, run the tests")
    s.add_argument("--bloomberg", action="store_true", help="install blpapi even if no Terminal is detected")
    s.add_argument("--no-bloomberg", action="store_true", help="never install blpapi")
    s.add_argument("--sample", action="store_true", help="import the sample trade blotter (data/sample/blotter_sample.csv) so the screens show data")
    s.add_argument("--recreate", action="store_true", help="delete and rebuild .venv")
    s.add_argument("--skip-tests", action="store_true")
    s.set_defaults(func=cmd_setup)

    t = sub.add_parser("start", help="start the app and open the browser")
    t.add_argument("--force-new", action="store_true", help="never reuse a running instance")
    t.add_argument("--no-sync", action="store_true", help="do not update from GitHub first")
    t.add_argument("--refresh-packages", action="store_true", help=argparse.SUPPRESS)
    t.set_defaults(func=cmd_start)

    dcm = sub.add_parser("doctor", help="check every prerequisite and say what to fix")
    dcm.add_argument("--bloomberg", action="store_true", help="require Bloomberg and test every request")
    dcm.add_argument("--tests", action="store_true", help="also run the test suite")
    dcm.add_argument("--no-git", action="store_true", help="skip the GitHub sync check")
    dcm.set_defaults(func=cmd_doctor)

    sub.add_parser("_load_sample", help=argparse.SUPPRESS).set_defaults(func=cmd_load_sample)

    f = sub.add_parser("freeze", help="(re)write requirements.txt from PACKAGES, for pip/CI use outside 2_launcher.py")
    f.set_defaults(func=cmd_freeze)
    return parser


def main(argv=None) -> int:
    args = build_parser().parse_args(sys.argv[1:] if argv is None else argv)
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    return args.func(args)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except SystemExit as exc:
        if isinstance(exc.code, str):
            say(exc.code)
            sys.exit(1)
        raise
    except KeyboardInterrupt:
        sys.exit(130)
